### PR TITLE
fix: invalid date when parsing it from html

### PR DESCRIPTION
**Pull request by jaikathuria**
# Changelog

1. Updated the timeout because it was causing a lot of images to fail to download
2. Created a separate method that handles the logic to get the date of the image
  a. This method will use 3 different options to get the date of the image 
    * `default` which would set the value to 1/1970, if none of the ways work, this would be set
    * `DateTimeOriginal` which would take the values from `metadata.DateTimeOriginal`
    * `CreateDate` which would take the values from `metadata.CreateDate`
    * `HTML` which would take the values from parsing the Google Photos page

### CODE REVIEW

**Comment by markcs** [comment]
Nice Fix.  @vikas5914  Can this be merged?

**Comment by vikas5914** [comment]
@markcs I will do it this weekend.

**Comment by skarekrow** [comment]
Fixed it for me here as well, thanks @jaikathuria!

**Comment by vikas5914** [comment]
@markcs, the rewrite is taking time. So, I will merge this for now.

**Pull request merged**
